name: 'Get Chuck Norris Joke'
description: 'Fetches a random Chuck Norris joke from an API'
inputs:
  url:
    description: 'The URL to fetch the joke from'
    required: true
outputs:
  joke:
    description: 'The fetched joke'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACTIONS_RUNNER_DEBUG: 'true'
    ACTIONS_STEP_DEBUG: 'true'
