name: Chuck Norris Joke

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CHUCK_API: "https://api.chucknorris.io/jokes/random"

jobs:
  get-joke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Enable Debugging
      run: |
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get a Chuck Norris Joke
      id: get_joke
      uses: ./.github/actions/get-chuck-norris-joke
      with:
        url: "https://api.chucknorris.io/jokes/random"

    - name: Display the Joke
      run: echo "Joke - ${{ steps.get_joke.outputs.joke }}"
